[tool.poetry]
name = "camprofiler"
version = "0.0.1"
description = "This guys is lazy he didn't write anything down here..."
authors = ["Hugo Ji <yugeji2@illinois.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.23.5"
matplotlib-ephys = "^0.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
